# Windows on these displays will always be stickied
# To find the index of a display, open a terminal emulator on the display to check and run 'sticky-display -print-display'
sticky_displays = [1]

# Regex RE2 syntax to ignore windows (WM_CLASS string can be found by running 'xprop WM_CLASS').
# window_ignore = [
#   ['WM_CLASS', 'WM_NAME'] = ['ignore all windows with this class', 'but allow those with this name']
# ]

################################################################################
[keys]                            # Key symbols can be found by running 'xev'. #
################################################################################

# Nothing here yet